repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [--line-length=90, --safe]
      exclude: 'patches/v*'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      max-line-length: 90
      exclude: 'patches/v*'
