[mypy]
python_version = 3.7
mypy_path = "stubs/:./tbottest/:./tbottest/tbotconfig/:../tbot/:../tbot/tbot/"

warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = false
incremental = true

check_untyped_defs = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_optional = true
warn_return_any = true
warn_unused_ignores = false

#[tbot*]
#ignore_missing_imports = True
