name: tbottest selftest CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies, doc-tools
        run: |
          python -m pip install --upgrade pip
          pip3 install --user pytest mypy paramiko termcolor2 pyserial coverage pytest-cov
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.TARGET_HOST }}
          SSH_USER: ${{ secrets.TARGET_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          echo "SSHUSER: $SSH_USER"
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
            Host $SSH_HOST
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no

            Host 192.168.1.113
              HostName 192.168.1.113
              User $SSH_USER
              ProxyJump $SSH_HOST
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
      - name: Run tbottest selftests
        run: |
          export COLUMNS=160
          # for unknown reasons termcolor2 get not found
          # but Install step shows, that it is installed
          export PYTHONPATH=/home/runner/.local/lib/python3.7/site-packages
          mkdir temp
          cd temp
          # set some git default values so git am works
          git config --global user.email "hs@denx.de"
          git config --global user.name "Heiko Schocher"
          ../scripts/create_setup.sh
          # test if ssh works
          echo "--------------------- try forwarder ------------------"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/staging.key pi@xeidos.ddns.net /home/pi/hello.sh
          echo "---------------------- try to login on lab -----------"
          ssh -o StrictHostKeyChecking=no -i '~/.ssh/staging.key' pi@192.168.1.113 /home/pi/hello.sh
          # correct path to keyfile
          sed -i "s|/home/\${username}/.ssh/id_rsa|~/.ssh/staging.key|g" tbotconfig/foo/tbot.ini
          echo "----- now try to login into lab with tbot setup and do all tests -----"
          tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -q -q tbotconfig.ci.tests.all
          # and test second build host
          tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -q -q tbotconfig.ci.testbh.bhall
          tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -f buildername:sisyphus -q -q tbotconfig.ci.testbh.bhall
